name: CMake Unit Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: cmake -B build && cmake --build build
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Run test target
        run: cmake --build build -- test
        env:
          CC: gcc-10
          CXX: g++-10